FROM --platform=linux/amd64 ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git ca-certificates liblzma-dev isolinux mtools \
    && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/ipxe/ipxe.git /ipxe
WORKDIR /ipxe/src
