services:
  http:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "8070:8070"
    volumes:
      - ./config:/srv/config:ro
      - ./data:/srv/data
    restart: unless-stopped
